const VIEW_NOTE ='VIEW_NOTE';
const ADD_NOTE ='ADD_NOTE';
const EDIT_NOTE ='EDIT_NOTE';
const DELETE_NOTE ='DELETE_NOTE';
const LOGOUT_USER ='LOGOUT_USER';
const ADD_USER ='ADD_USER';
const LOGIN_USER ='LOGIN_USER';

export {VIEW_NOTE, ADD_NOTE, EDIT_NOTE,DELETE_NOTE,LOGOUT_USER,ADD_USER,LOGIN_USER}